server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称用于bingding整合
          type: rabbit # 消息组件类型
          environment:  #  设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange  # 表示要使用的Exchange名称的定义
          content-type: application/json  # 设置消息类型，本次为接送，文本设置text/plin
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          #group: atiguiguiA # 分组设置

eureka:
  client:   # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳时间 默认是30秒
    lease-expiration-duration-in-seconds: 5  # 设置持久化时间  默认是90秒
    instance-id: reciver-8802.com   # 在信息列表时显示主机名称
    prefer-ip-address: true  # 访问的路径变为IP地址

