server:
  port: 9527
spring:
  application:
    name: cloug-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心动态创建路由的功能利用微服务名进行路由
      routes:
        - id: payment_routh   #路由的id，没有固定规则，建议配合服务唯一
#          uri: http://localhost:8001   #陪陪后提供服务的路由地址？
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payement/get/**   # 断言，路径相匹配的路由地址

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payement/lb/**
#            - After=2020-05-11T12:06:54.006+08:00[Asia/Shanghai]
#            - Header=X-Request-Id, \d+
#            - Cookie=username,zzyy



eureka:
  instance:
    hostname: cloud-gateway-server
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka

