server:
  port: 80

# 设置Eureka client 设置
spring:
  application:
    name: cloud-order-service

    #   zipkin 监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样值介于0到1之间，表示全部采集


eureka:
  client:
    fetch-registry: true # 是否从EurekaServer 抓取没有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon自动负载均衡
    register-with-eureka: true # 是否将自己注册进eurekaService 默认为true
    service-url:
      # 单机版
      defaultZone: http://localhost:7001/eureka
#集群版
#        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka