spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/imooc-mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'
#mybatis 配置逻辑删除  全局配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
